### PR TITLE
Add 2017 BU coefficients

### PR DESCRIPTION
**Pull request by junousi**
Add per-flavor BU coefficients, to be taken into use at start of 2017.

### CODE REVIEW

**Review by oscarkraemer — COMMENTED** [review]
Should windows flavours be in the list?

**Comment by junousi** [comment]
They're currently limited to internal testing, so no.

**Review by oscarkraemer — COMMENTED** [review]
There is an error: hpc.largemem.westmere  memory is wrong.

**Comment by junousi** [comment]
Good catch! Updated.

**Review by oscarkraemer — APPROVED** [review]
Looks good

**Pull request merged**
